### ISSUE TITLE
Issue in Creating Subscrioptions using PowerShell

### ISSUE THREAD

**Issue by erajendar** [Microsoft/ReportingServicesTools#107]
I want to report the bug

Hi - I am trying to create the subscriptions using Powershell command. I want to read the source report subscription and create it on destination report. Both Soure/Destination report servers have SSRS 2016 version  but I am getting the conversion error.  Please advise me how to resolve it.

I am using below command from Powershell:

PS C:\Windows\system32> Get-RsSubscription -ReportServerUri 'http://datauat/INSIGHTS_wsvc' -Path '/Mining Operations/BI Solomon Consolidated Ops Report/BI_Solomon_ConsolidatedOpsReport' | Set-RsSubscription -ReportServerUri 'http://localhost/Reportserver_SQL2016' -Path '/Mining Operations/BI Solomon Consolidated Ops Report/BI_Solomon_ConsolidatedOpsReport' 

I am receiving below error.  Please help me in resolving it.

Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with 

value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy9sql2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy9sql2016_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: Exception occurred while 

creating subscription! Cannot convert argument "ExtensionSettings", with value: 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy9sql2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy9sql2016_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.MethodException: 

Cannot convert argument "ExtensionSettings", with value: 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy9sql2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy9sql2016_ReportService2010_asmx.ExtensionSettings"." ---> 

System.Management.Automation.PSInvalidCastException: Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy9sql2016_ReportService2010_asmx.ExtensionSettings".

   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)

   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider 

formatProvider, TypeTable backupTable)

   at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object )

   --- End of inner exception stack trace ---

   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)

   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

At line:1 char:1

+ Get-RsSubscription -ReportServerUri 'http://uat/INSIGHTS_wsvc' -Path '/Minin ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription

I am using Powershell version 4.0

**Comment by ClaudioESSilva** [comment]
Hi @erajendar, can you tell us what version of the ReportingServicesTools module you are using?

**Comment by erajendar** [comment]
Hi Claudio - Sorry I don't remember which version I installed.  But running of below command is not displaying version number
Get-Command -Module ReportingServicesTools
Is there any other way to know the verison.

thanks

**Comment by erajendar** [comment]
I got it.  I am using 0.0.2.9 version.

**Comment by ClaudioESSilva** [comment]
@erajendar are both Reporting Services the 2016 version?

**Comment by erajendar** [comment]
Yes both are 2016 version

**Comment by ClaudioESSilva** [comment]
Thanks.
The error points to the ExtensionSettings this is relative to the `DeliverySettings` which contains the `Extension` and `ParameterValues`. Are your reports exactly the same? With same parameters?

I found this error before when trying to apply parameters where the destination report hasn't it.

Also, please try to Export the subscriptions and import them (I expect to see the same behaviour, but just to double check).

```
Get-RsSubscription -ReportServerUri $reportServerUri -Path "/instances" | Export-RsSubscriptionXml -Path "$downloadFolder\AllSubscriptions.xml"

Import-RsSubscriptionXml -ReportServerUri $reportServerUri "$downloadFolder\AllSubscriptions.xml" | Set-RsSubscription -ReportServerUri $reportServerUri -Path "/instances"
```

**Comment by erajendar** [comment]
Hi Claudio - Thanks for reply.  I am trying to create the subscription on identical reports(same parameters) which exist on two different servers.
Export subscription command working fine and exporting the subscriptions to xml file. However, while executing the Import subscription command throwing an error:

Below command working fine:
Get-RsSubscription -ReportServerUri 'http://datauat/INSIGHTS_wsvc' -Path '/Mining Operations/BI Solomon Consolidated Ops Report/BI_Solomon_ConsolidatedOpsReport'| Export-RsSubscriptionXml -Path 'C:\$Working\Temp\SSRSMigration\AllSubscriptions.xml'

I tried Import command by keep the report serverui as source server onetime and destination server one time as am not very sure which one to keep and every time I got different error as shown below:
1. PS C:\Windows\system32> Import-RsSubscriptionXml -ReportServerUri 'http://localhost/Reportserver_SQL2016' 'C:\$Working\Temp\SSRSMigration\AllSubscriptions.xml' | Set-RsSubscription -ReportServerUri 'http://localhost/Reportserver_SQL2016' -Path '/Mining Operations/BI Solomon Consolidated Ops Report/BI_Solomon_ConsolidatedOpsReport'
Exception occurred while creating subscription! Exception calling "CreateSubscription" with "6" argument(s): "System.Web.Services.Protocols.SoapException: An attempt has been made to use a 
delivery extension that is not registered for this report server. ---> Microsoft.ReportingServices.Diagnostics.Utilities.DeliveryExtensionNotFoundException: An attempt has been made to use 
a delivery extension that is not registered for this report server.
   at Microsoft.ReportingServices.Library.ReportingService2005Impl.CreateSubscription(String Report, ExtensionSettings ExtensionSettings, Boolean isDataDriven, DataRetrievalPlan 
DataRetrievalPlan, String Description, String EventType, String MatchData, ParameterValueOrFieldReference[] Parameters, Guid batchId, String& SubscriptionID)
   at Microsoft.ReportingServices.Library.ReportingService2005Impl.CreateSubscription(String Report, ExtensionSettings ExtensionSettings, Boolean isDataDriven, DataRetrievalPlan 
DataRetrievalPlan, String Description, String EventType, String MatchData, ParameterValueOrFieldReference[] Parameters, String& SubscriptionID)
   at Microsoft.ReportingServices.WebServer.ReportingService2010.CreateSubscription(String ItemPath, ExtensionSettings ExtensionSettings, String Description, String EventType, String 
MatchData, ParameterValue[] Parameters, String& SubscriptionID)"
At \\fmg.local\perth\usv-fr\rerebathini\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\Functions\CatalogItems\Set-RsSubscription.ps1:151 char:13
+             throw (New-Object System.Exception("Exception occurred while creatin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Exception occurred while creating subscription! Exception calling "CreateSubscription" with "6" argument(s): "System.Web.Services.Protocols.SoapException: An a 
   ttempt has been made to use a delivery extension that is not registered for this report server. ---> Microsoft.ReportingServices.Diagnostics.Utilities.DeliveryExtensionNotFoundException  
  : An attempt has been made to use a delivery extension that is not registered for this report server.
       at Microsoft.ReportingServices.Library.ReportingService2005Impl.CreateSubscription(String Report, ExtensionSettings ExtensionSettings, Boolean isDataDriven, DataRetrievalPlan DataRet 
   rievalPlan, String Description, String EventType, String MatchData, ParameterValueOrFieldReference[] Parameters, Guid batchId, String& SubscriptionID)
       at Microsoft.ReportingServices.Library.ReportingService2005Impl.CreateSubscription(String Report, ExtensionSettings ExtensionSettings, Boolean isDataDriven, DataRetrievalPlan DataRet 
   rievalPlan, String Description, String EventType, String MatchData, ParameterValueOrFieldReference[] Parameters, String& SubscriptionID)
       at Microsoft.ReportingServices.WebServer.ReportingService2010.CreateSubscription(String ItemPath, ExtensionSettings ExtensionSettings, String Description, String EventType, String Ma 
   tchData, ParameterValue[] Parameters, String& SubscriptionID)"


2. PS C:\Windows\system32> Import-RsSubscriptionXml -ReportServerUri 'http://datauat/INSIGHTS_wsvc' 'C:\$Working\Temp\SSRSMigration\AllSubscriptions.xml' | Set-RsSubscription -ReportServerUri 'http://localhost/Reportserver_SQL2016' -Path '/Mining Operations/BI Solomon Consolidated Ops Report/BI_Solomon_ConsolidatedOpsReport'
Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3SQL2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3SQL2016_ReportService2010_asmx.ExtensionSettings"."
At \\fmg.local\perth\usv-fr\rerebathini\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\Functions\CatalogItems\Set-RsSubscription.ps1:151 char:13
+             throw (New-Object System.Exception("Exception occurred while creatin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.Auto 
   generatedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.W  
  ebServiceProxy3SQL2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_Report   
 Service2010_asmx.ExtensionSettings" value of type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1TS_wsvc_ReportService2010_asmx.ExtensionSettings"     
to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3SQL2016_ReportService2010_asmx.ExtensionSettings"."

**Comment by ClaudioESSilva** [comment]
Hi @erajendar ,

Which type of delivery setting are you trying to use? 
Email? if so, do you have the email configured?

I'm asking because of the following error message:
```
 An attempt has been made to use a delivery extension that is not registered for this report server.
```

**Comment by erajendar** [comment]
Thanks Claudio - I am using Email delivery. But the SMTP server is not yet configure.  Will configure it and let you know how it goes.  Thanks for help so far.  thanks

**Comment by erajendar** [comment]
Yes, It has done magic.  After configuring the SMTP server import/export commands are working fine:).  Thanks for help.
However, below command is still throwing the same error:

PS C:\Windows\system32> Get-RsSubscription -ReportServerUri 'http://datauat/INSIGHTS_wsvc' -Path '/Mining Operations/BI Solomon Consolidated Ops Report/BI_Solomon_ConsolidatedOpsReport' | Set-RsSubscription -ReportServerUri 'http://localhost/Reportserver_SQL2016' -Path '/Mining Operations/BI Solomon Consolidated Ops Report/BI_Solomon_ConsolidatedOpsReport'

**Comment by ClaudioESSilva** [comment]
I had the same problem after a fresh SSRS 2017 install 😄 
Glad you have a way to workaround.

Regarding the Get | Set is the exact same error as before? Can you "re-paste" it, please?

**Comment by erajendar** [comment]
Thanks Claudio.  Please see below error when using Get|Set

Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with 

value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1SQL2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1SQL2016_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: Exception occurred while 

creating subscription! Cannot convert argument "ExtensionSettings", with value: 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1SQL2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1SQL2016_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.MethodException: 

Cannot convert argument "ExtensionSettings", with value: 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1SQL2016_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1SQL2016_ReportService2010_asmx.ExtensionSettings"." ---> 

System.Management.Automation.PSInvalidCastException: Cannot convert the 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" value of type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3TS_wsvc_ReportService2010_asmx.ExtensionSettings" to type 

"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1SQL2016_ReportService2010_asmx.ExtensionSettings".

   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)

   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider 

formatProvider, TypeTable backupTable)

   at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object )

   --- End of inner exception stack trace ---

   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)

   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

At line:1 char:1

+ Get-RsSubscription -ReportServerUri 'http://datauat/INSIGHTS_wsvc' -Path '/Minin ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription

**Comment by marcosfreccia** [comment]
I am having the same problem. Copying Subscriptions from SSRS 2016 to SSRS 2017 gives me this error. 


Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: Exception occurred while creating subscription! 
Cannot convert argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for 
"CreateSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.MethodException: Cannot convert argument 
"ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.PSInvalidCastException: Cannot convert 
the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable 
backupTable)
   at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
At line:5 char:1
+ Get-RsSubscription -ReportServerUri $SourceSSRS -Path "/MySSRSFolder/Help ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription

**Comment by TKeviv** [comment]
Below Example under Import-RsSubscription.ps1 is not working as Set-RsSubscription does not have the "-Path" argument defined in the latest version. I think the problem is similar to what is mentioned in this thread hence mentioning it here. 

EXAMPLE
            Import-RsSubscriptionXml .\MySubscriptions.xml | Set-RsSubscription -Path /Example/Report

            Description
            -----------
            This command will import the subscriptions contained in .\MySubscriptions.xml, recreate any SRSS specific properties
            and pipe the results to Set-RsSubscription which will add them to the /Example/Report report

**Comment by hacksterx** [comment]
Having the same importing subscptions from SSRS 2008 to SSRS2016.

> Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings", for 
"CreateSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings"."
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools-master\ReportingServicesTools\Functions\CatalogItems\Copy-RsSubscription.ps1:150 char:13
> + throw (New-Object System.Exception("Exception occurred wh ...
 > + CategoryInfo          : OperationStopped: (:) [], Exception
 > + FullyQualifiedErrorId : Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.Exten 
   sionSettings", for "CreateSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings": "Cannot convert the "Microsoft.PowerShell.Commands.NewWebserviceProx  
  y.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings" value of type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings" to type "Microso   
 ft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy7tserver_ReportService2010_asmx.ExtensionSettings"."

**Comment by arcus4** [comment]
Ps Version 5.1.19041.1320 and OS of our $SourceServerURI is Windows Server 2012 R2 with Ps Version 4.0. This bug seems to be really unsolved.
