### ISSUE TITLE
Copy Subscription does not work

### ISSUE THREAD

**Issue by shardul811** [Microsoft/ReportingServicesTools#172]
**My Command: Get-RsSubscription -ReportServerUri "http://sourceSSRS/ReportServer" -rsitem "/Folder" | Copy-RsSubscription -ReportServerUri 'http://DestSSRS/ReportServer' -RsFolder "/DestinationFolder"**

When i run the Get-RsSubscription, it does show me the subscription information. However, the above command fail.
Source SSRS 2014 --> Destination SSRS 2014
Here is the Error Message:
Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy13tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy13tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: Exception occurred while creating 
subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy13tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy13tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.MethodException: Cannot convert 
argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" 
to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy13tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy13tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.PSInvalidCastException: Cannot 
convert the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy11tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy13tServer_ReportService2010_asmx.ExtensionSettings".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, 
TypeTable backupTable)
   at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
At line:2 char:1
+ Get-RsSubscription -ReportServerUri "http://SourceSSRS/ReportServer ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription

**Comment by MikeyMing** [comment]
2005 > 2016

Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument 
"ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings", for 
"CreateSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy4tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert 
the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy4tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: Exception occurred 
while creating subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings", for "CreateSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy4tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy4tServer_ReportService2010_asmx.ExtensionSettings"." ---> 
System.Management.Automation.MethodException: Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings", for "CreateSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy4tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy4tServer_ReportService2010_asmx.ExtensionSettings"." ---> 
System.Management.Automation.PSInvalidCastException: Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy79tServer_ReportService2005_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy4tServer_ReportService2010_asmx.ExtensionSettings".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider 
formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
At \SaveSSRS2008Files.ps1:192 char:9
+         Get-RsSubscription $report.ReportPath -ReportServerUri $($report.SourceR ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription

**Comment by jzabroski** [comment]
This issue appears to be related to a forthcoming patch I will make. See #97

**Comment by jzabroski** [comment]
@MikeyMing  What's the output of Get-RsSubscription *before* you pipe it to Copy-RsSubscription?

**Comment by sherlockspreadsheets** [comment]
I am having a similar issue with `GET-RsSubscription` piped to `COPY-RsSubscription` ...

CMD_Trial1: `Get-RsSubscription -ReportServerUri $reportServerUri_src -RsItem "/fsqa" | Copy-RsSubscription -ReportServerUri $reportServerUri_tgt -RsItem "/fsqa" -verbose`

MSG_Trial1:

```
VERBOSE: Establishing proxy connection to http://gcod050/ReportServer/ReportService2010.asmx...
VERBOSE: Validating if target report exists...
VERBOSE: Performing the operation "Creating new subscription" on target "/fsqa".
VERBOSE: Creating Subscription...
...
Lots of System.Exception messages such as...
	* Exception while retrieving subscription properties!
	* Exception occurred while creating subscription!
	* Cannot convert argument "ExtensionSettings", with value: "Microsoft.Power
	Shell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"
	* Cannot convert the "Microsoft.Power
	Shell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"
	* 
...
VERBOSE: Validating if target report exists...
WARNING: Can't find the report //PO Samples for Testing. Skipping.
```

**Comment by jzabroski** [comment]
@jtarquino  needs to merge my fix for this in #97

**Comment by sherlockspreadsheets** [comment]
I also tried adding a specific report item (instead of the folder path).  But that did not work either. 

CMD_Trial2: `Get-RsSubscription -ReportServerUri $reportServerUri_src -RsItem "/fsqa/PO Samples for Testing" | Copy-RsSubscription -ReportServerUri $reportServerUri_tgt -RsItem "/fsqa/PO Samples for Testing"`

MSG_Trial2:

```
VERBOSE: Establishing proxy connection to http://gcod050/ReportServer/ReportService2010.asmx...
VERBOSE: Validating if target report exists...
VERBOSE: Performing the operation "Creating new subscription" on target "/fsqa/PO Samples for Testing".
VERBOSE: Creating Subscription...
...
Lots of System.Exception messages such as...
	* 
...
VERBOSE: Validating if target report exists...
VERBOSE: Performing the operation "Creating new subscription" on target "/fsqa/PO Samples for Testing".
VERBOSE: Creating Subscription...
...
More System.Exception messages such as...
	* 
...
```

**Comment by jtarquino** [comment]
@jzabroski I was under the impression you were going to add tests in that PR, if you don't have the chance let me know and I can review it to merge it

**Comment by jtarquino** [comment]
@jzabroski the second part pending was the update to the function documentation and sample

**Comment by sherlockspreadsheets** [comment]
Does it matter that my source and target RS are different versions of SSRS 2016?  Or is the only fix to wait for an update to the cmdlet?  

> $reportServerUri_src
> http://gcod049/ReportServer
> Microsoft SQL Server Reporting Services Version 13.0.5264.1

and

> $reportServerUri_tgt
> http://gcod050/ReportServer
> Microsoft Power BI Report Server Version 15.0.2.557

**Comment by sherlockspreadsheets** [comment]
I am also getting this error.  The GET works just fine.  But I have had an issue both COPY (menioned previously) and SET (as seen in this post).  Am I doing something wrong?  


PS:  ```
Get-RsSubscription -ReportServerUri $reportServerUri_src -Path "/fsqa" | Where-Object {$_.Subscr
iptionId -eq '4c1539c4-9e0f-42c4-aace-b493c96ec2e4'} | Set-RsSubscription -StartDateTime "2/13/2019 1:20pm" -verbose
```

> VERBOSE: Establishing proxy connection to http://localhost/reportserver/ReportService2010.asmx...
> Failed to establish proxy connection to http://localhost/reportserver/ : Failed to establish proxy connection to
> http://localhost/reportserver/ReportService2010.asmx : There was an error downloading
> 'http://localhost/reportserver/ReportService2010.asmx'.
> At C:\Users\bl0040ep\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\Functions\Utilit
> ies\New-RsWebServiceProxy.ps1:83 char:17
> +                 throw (New-Object System.Exception("Failed to establish proxy co ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], Exception
>     + FullyQualifiedErrorId : Failed to establish proxy connection to http://localhost/reportserver/ : Failed to estab
>    lish proxy connection to http://localhost/reportserver/ReportService2010.asmx : There was an error downloading 'ht
>   tp://localhost/reportserver/ReportService2010.asmx'.

**Comment by jzabroski** [comment]
@sherlockspreadsheets  This is 100% the wrong thread to post stuff about set-rssubscription.  Create a new ticket.

**Comment by sherlockspreadsheets** [comment]
@jzabroski - Moved questioned to new ticket #223.  Deleted question in this post.

**Comment by sherlockspreadsheets** [comment]
@jzabroski - Good day to you.  I was just checking in on the status of the issue I report yesterday, not being able to successfully run the Copy-RsSubscription script to copy subscriptions from one server to another.

**Comment by sherlockspreadsheets** [comment]
@jzabroski , @jtarquino - The "Copy" functionality would be of tremendous value to my daily administrative work.  What is the status for of the suggested fix, regarding the merge from jzabroski in #97?

**Comment by jtarquino** [comment]
@sherlockspreadsheets  thre are open comments https://github.com/Microsoft/ReportingServicesTools/pull/186 , feel free to resolve them and send a new iteration

**Comment by JamesDBartlett** [comment]
@sherlockspreadsheets FYI, #186 has been merged into master. Happy days are here!

**Comment by sherlockspreadsheets** [comment]
@JamesDBartlett - Sorry but I am just now seeing your comment. I have installed the latest RSTools version (0.0.5.6), uninstalled my previous version (0.0.5.1), and did a full start on my PC. I am still getting the exact same error message as posted on the original poster reported on this issue. The error message, along with other messages, says: "Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value:". 

I have a subscription on one server and the GET cdmlet works. The COPY cmdlet gives the error. Am I doing something wrong? Is there a way to copy subscriptions? That would be the most wonderful thing.

**Comment by jzabroski** [comment]
Use Fiddler and spy what value is coming back from the API.  I had tried to handle various 2005 to 2016 upgrade paths but I could only test the ones I personally dealt with.  I believe the code if you read it handles the office extension differences that were made to accomodate MSFT monopoly.

**Comment by sherlockspreadsheets** [comment]
@jzabroski - I downloaded fiddler but I'm not familiar enough with how to use it test the API. That said I did read the `Copy-RsSubscription.ps1` file. I am no posh expert, but reading the code gave me the idea. Instead of using a different server from GET to COPY. I setup a scenario to copy subscriptions from one Folder to another on the same server-- that worked; It added the subscriptions to the target report. I then tried GET and COPY to the same Folder-- that worked; It duplicated the subscriptions on the same report. 

The document example indicates you can Copy from one server to another. But I can continue to get the error message. What should I do different? Or how should I use fiddler? 

>  "Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tserver_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription"

`PS C: > get-help Get-RsSubscription -examples
...
Get-RsSubscription -ReportServerUri 'http://localhost/ReportServer_sql14' -RsItem '/path/to/my/oldReport' | Copy-RsSubscription -ReportServerUri 'http://remote-machine:8080/reportserver_sql16' -RsItem '/path/to/newReport'
...
`

**Comment by jzabroski** [comment]
The issue is that you need a massaging step to massage the ExtensionSettings, since the ExtensionSettings values changed between 2005 and 2012.  I already explained that.

For Fiddler, you need to use the Inspector tab of the request/response.   In the left hand audit trail pane you need to look for the specific HTTP SOAP requests coming from your machine to the SSRS instance.

I'm sorry this is not easy for you as a beginner to these recommended tools.  I recommend using YouTube for a basic Fiddler Soap debugging tutorial.  Alternatively, if you work in an organization with other developers, perhaps ask them if any of them have used Fiddler before.  It's a very popular tool in Windows shops.

**Comment by arcus4** [comment]
Ps Version 5.1.19041.1320 and OS of our $SourceServerURI is Windows Server 2012 R2 with Ps Version 4.0. This bug seems to be really unsolved.
