### ISSUE TITLE
Get-RsSubscription Cannot convert argument  "ExtensionSettings"

### ISSUE THREAD

**Issue by Johno-AU** [microsoft/ReportingServicesTools#232]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Exception message
Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument 
"ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" 
to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert 
the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: 
Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" 
to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert 
the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> 
System.Management.Automation.MethodException: Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings", for "CreateSubscription" 
to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert 
the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> 
System.Management.Automation.PSInvalidCastException: Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings".
at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject 
originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object )
--- End of inner exception stack trace ---
at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
at Copy-RsSubscription<Process>(Closure , FunctionContext )
--- End of inner exception stack trace ---
--- End of inner exception stack trace ---
At line:1 char:1
+ Get-RsSubscription -ReportServerUri $SourceServerURI -RsItem '/Config ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Attempting to copy subscriptions from SQL 2008 R2 to SQL 2016.

$SourceServerURI = 'http://sourceServer/Reportserver'
$TargetServerURI =  'http://TargetServer/Reportserver'
Get-RsSubscription -ReportServerUri $SourceServerURI -RsItem '/ConfigMgr_C01/CSC/HW Inv report for Asset Mgmt' | 
Copy-RsSubscription -ReportServerUri $TargetServerURI -RsItem '/ConfigMgr_C01/CSC/HW Inv report for Asset Mgmt'

**What is the expected behavior?**
Subscriptions copied from reports hosted on $SourceServerURI  to new reports hosted on $TargetServerURI

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
0.0.4.9 6/2/19

**Comment by arcus4** [comment]
It seems to be unsolved. Today we attempted to copy some report subscriptions from SQL2016 to SQL2019 ReportServer.

**Comment by jyao-mag** [comment]
Get the same error when trying to copy subscriptions from an SSRS 2016 report to the same report which is migrated to a SSRS 2017 box.
