### ISSUE TITLE
migrating data-driven subscriptions fails

### ISSUE THREAD

**Issue by Mishtry** [microsoft/ReportingServicesTools#240]
**Do you want to request a *feature* or report a *bug*?** A bug

**What is the current behavior?**
When migrating data-driven subscriptions from one server to another, getting an error that it can convert the extensionSettings:

Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for "CreateDataDrivenSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: Exception occurred while creating subscription! 
Cannot convert argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for 
"CreateDataDrivenSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.MethodException: Cannot convert 
argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for 
"CreateDataDrivenSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.PSInvalidCastException: Cannot convert 
the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable 
backupTable)
   at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
At line:1 char:1
+ Get-RsSubscription -ReportServerUri 'https://xxxxxx...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription
 
Get-RsSubscription : System.Exception: Exception while retrieving subscription properties! Exception occurred while creating subscription! Cannot convert argument "ExtensionSettings", with value: 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for "CreateDataDrivenSubscription" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Exception: Exception occurred while creating subscription! 
Cannot convert argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for 
"CreateDataDrivenSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.MethodException: Cannot convert 
argument "ExtensionSettings", with value: "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings", for 
"CreateDataDrivenSubscription" to type "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings": "Cannot convert the 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings"." ---> System.Management.Automation.PSInvalidCastException: Cannot convert 
the "Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" value of type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy5tServer_ReportService2010_asmx.ExtensionSettings" to type 
"Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3tServer_ReportService2010_asmx.ExtensionSettings".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable 
backupTable)
   at CallSite.Target(Closure , CallSite , Object , String , Object , Object , Object , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
At line:1 char:1
+ Get-RsSubscription -ReportServerUri 'https://xxxxxxxx...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RsSubscription
 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Using powershel, i tried copying the subcription from one server through Get-RsSubscription and creating the subsctiption to another server through Set-RsSubscription.

**What is the expected behavior?**

Create the subscriptions in the new server

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

Name                           Value                                                                                                                                                                              
----                           -----                                                                                                                                                                              
PSVersion                      5.1.17134.765                                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                            
BuildVersion                   10.0.17134.765                                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                                
SerializationVersion           1.1.0.1

First time running the scripts

**Comment by Mishtry** [comment]
Typo: When migrating data-driven subscriptions from one server to another, getting an error that it cannot* convert the extensionSettings:
