### ISSUE TITLE
Report Server WMIProviderException

### ISSUE THREAD

**Issue by 90301** [microsoft/ReportingServicesTools#328]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

Running

```
rsconfig -c -s "$($env:COMPUTERNAME)" -d ReportServer -a Windows -t
```
results in the error:

```
RSConfig.exe : Microsoft.ReportingServices.WmiProvider.: Report Server WMI Provider error:
At line:3 char:1
+ & "rsconfig" -c -s "$($env:COMPUTERNAME)" -d ReportServer -a Windows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (Microsoft.Repor...Provider error::String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
Invalid namespace ---> System.Management.ManagementException: Invalid namespace
at System.Management.ManagementException.ThrowWithExtendedInfo(Management
Status errorCode)
at System.Management.ManagementScope.InitializeGuts(Object o)
at System.Management.ManagementScope.Initialize()
at Microsoft.ReportingServices.WmiProvider.WmiProviders.GetInstance(String machineName, String instanceName, RSWmi
Namespaces rsNamespace, ConnectionOptions connOptions, ObjectGetOptions getOptions, String version)
--- End of inner exception stack trace ---
at Microsoft.ReportingServices.WmiProvider.WmiProviders.GetInstance(String machineName, String instanceNa
me, RSWmiNamespaces rsNamespace, ConnectionOptions connOptions, ObjectGetOptions getOptions, String version)
at Microsoft.ReportingServices.WmiProvider.WmiProviders.GetReportServerAdmin(String machineName, String instanceName,
ConnectionOptions connOpt
ions, ObjectGetOptions getOptions, String version)
at Microsoft.ReportingServices.WmiProvider.WmiProviders.GetReportServerAdmin(String machineName, String instanceName,
ConnectionOptions connOptions, ObjectGetOptions getOptions)
at Microsoft.Report
ingServices.ConfigManagement.ConfigFileApp.ConnectToWmi()
at Microsoft.ReportingServices.ConfigManagement.ConfigFileApp.InstanceMain()
at Microsoft.ReportingServices.BaseCmdLine.CommandLineMain(String[] args, BaseCmdLine instance)
```

* The database (Schema?) "ReportServer" exists
* The users / passwords are correct.
* Database is on the same machine as the powershell script

**What is the expected behavior?**

While we are not sure exactly what this is supposed to do (we can't track down who wrote the script).

We know that if something is incorrect, we at least need a better error message, but the error we are getting looks like something a user shouldn't get.

I think this has something to do with setting credentials on the report server.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
Windows Server 2016
Version          : 5.1.14393.3866
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)

Happy to help with additional information, if you need it, let us know.

**Comment by 90301** [comment]
Ok, it appears that you need to specify the instance. using -i SSMS fixed the issue.
