### ISSUE TITLE
Write-RsRestCatalogItem does not accept xslm files

### ISSUE THREAD

**Issue by AlexAlex1337** [microsoft/ReportingServicesTools#349]
I can upload a xlsx file with Write-RsRestCatalogItem but when I try it with a xlsm file I receive this error:
![image](https://user-images.githubusercontent.com/78158356/135234557-1581887b-f652-4eea-bdeb-64e96c85b292.png)

I can manually (in PBIRS) upload the xslm without any problems:
![image](https://user-images.githubusercontent.com/78158356/135234867-22db3bf7-44c5-4aa0-b70b-319625a1f17f.png)

Is there a different function than Write-RsRestCatalogItem for xslm files? Or does the function needs an update to support xslm files?

**Comment by AlexAlex1337** [comment]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Uploading of xlsm files is not possible with Write-RsRestCatalogItem. Manual uploading to PBIRS is possible.
When I rename the file from .xlsm to .xlsx I can upload the file with Write-RsRestCatalogItem.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
PS C:\> Write-RsRestCatalogItem -ReportPortalUri 'https://PBIRS-URL/Reports' -Path 'C:\Downloads\004 - Fehlteilliste Einkauf.xlsm' -RsFolder '/LWT'

Write-RsRestCatalogItem : System.Exception: Failed to create catalog item: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
   --- End of inner exception stack trace ---
At line:1 char:1
+ Write-RsRestCatalogItem -ReportPortalUri 'https://PBIRS-URL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-RsRestCatalogItem

PS C:\> Write-RsRestCatalogItem -ReportPortalUri 'https://PBIRS-URL/Reports' -Path 'C:\Downloads\004 - Fehlteilliste Einkauf.xlsx' -RsFolder '/LWT'

Same file - just renamed to xlsx gets uploaded successfully

**What is the expected behavior?**
That the xlsm file gets deployed to the PBIRS.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
PSVersion                      5.1.18362.1801
Script     0.0.6.7    ReportingServicesTools
PBIRS    Version 1.12.7977.29537 (September 2021)
OS of my laptop/notebook: Windows 10. the server runs windows server (dont know the exact version)

![image](https://user-images.githubusercontent.com/78158356/143011562-b6335f8d-b69d-422b-a5fc-f93347d9fd57.png)

**Comment by AlexAlex1337** [comment]
Hello? Any news on this bug? It has been over 1 year since I reported it.

**Comment by AlexAlex1337** [comment]
Hello jtarquino, is there a way to get actual support from MS for this project? It is almost 1.5 years since I reported this bug and we still have to update xslm files manually on our PBIRSs, instead of with a Release Pipeline in Devops.

**Comment by jtarquino** [comment]
We welcome contributions from the community in order to enhance the functionality of the functions.
I would like to invite you to submit a pull request with the proposed changes and we will review it.

**Comment by AlexAlex1337** [comment]
I do not know how to write code for your program.

**Comment by Periscope-NZ** [comment]
The solution might be as simple as adding a line for .xlsm to the [Get-ItemType](https://github.com/microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Common/Get-ItemType.ps1) function. It is not currently listed there.

**Comment by AlexAlex1337** [comment]
> The solution might be as simple as adding a line for .xlsm to the [Get-ItemType](https://github.com/microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Common/Get-ItemType.ps1) function. It is not currently listed there.

Sounds good to me - I hope the developers find time to look at this eventually. But it seems there is almost no interest in Microsoft to work on this tool.

**Comment by Periscope-NZ** [comment]
I know the feeling, it is very much "self-service" right now. I don't have the confidence in my Powershell skills to make pull requests myself just yet.

**Comment by Periscope-NZ** [comment]
I had a go at updating the Get-ItemType function and it seemed to fix your issue - I was able to upload an XLSM file without any errors to our PowerBI server. I am going to have a go creating my first Pull Request now!
